require 'spec_helper'

describe "StaticPages" do
  
  # the below describes the default spec that is generated by the 
  # system
  #describe "GET /static_pages" do
  #  it "works! (now write some real specs)" do
      # Run the generator again with the --webrat flag if you want to use webrat methods/matchers
  #   get static_pages_index_path
  #   response.status.should be(200)
  #  end
  #end


  describe "GET home page" do
    it "should have 'stores' in it's home page name " do
      visit '/static_pages/home' do
        expect(page).to have_content('Stores')
      end
    end
  end

end
