require 'spec_helper'

describe "StaticPages" do
  
  # the below describes the default spec that is generated by the 
  # system
  #describe "GET /static_pages" do
  #  it "works! (now write some real specs)" do
      # Run the generator again with the --webrat flag if you want to use webrat methods/matchers
  #   get static_pages_index_path
  #   response.status.should be(200)
  #  end
  #end


  describe "home page" do
    it "should have 'Stores' in it's home page name " do
      visit '/static_pages/home' 
      expect(page).to have_content('Stores')      
    end

    it "should have the title 'Stores4 App'" do
      visit '/static_pages/home' 
      expect(page).to have_title('Stores4 App')      
    end

    it "should not have a custom page title" do
      visit '/static_pages/home'
      expect(page).not_to have_title('| Home')
    end
  end


  describe "contact page" do
    it "should have 'Contact Us' in it's contact page name " do
      visit '/static_pages/contact' 
      expect(page).to have_content('Contact Us')      
    end

    #JUst FYI, have_content even works with substring
    it "should have 'Contact' in it's contact page name " do
      visit '/static_pages/contact' 
      expect(page).to have_content('Contact')      
    end

    it "should have the title 'Stores4 App | Contact Us'" do
      visit '/static_pages/contact' 
      expect(page).to have_title('Stores4 App | Contact Us')      
    end
  end

  describe "About page" do
    it "should have 'About Us' in the about page" do
      visit '/static_pages/about'
      expect(page).to have_content('About Us')
    end

    # Just FYI, have_title even works for substring
    it "should have the title 'About Us'" do
      visit '/static_pages/about' 
      expect(page).to have_title('About Us')      
    end    

    it "should have the title 'Stores4 App | About Us'" do
      visit '/static_pages/about' 
      expect(page).to have_title('Stores4 App | About Us')      
    end

  end

end
