require 'spec_helper'

describe "StaticPages" do
  
  # the below describes the default spec that is generated by the 
  # system
  #describe "GET /static_pages" do
  #  it "works! (now write some real specs)" do
      # Run the generator again with the --webrat flag if you want to use webrat methods/matchers
  #   get static_pages_index_path
  #   response.status.should be(200)
  #  end
  #end


  describe "home page" do
    it "should have 'Stores' in it's home page name " do
      visit '/static_pages/home' 
      expect(page).to have_content('Stores')      
    end

    it "should have the title 'Home'" do
      visit '/static_pages/home' 
      expect(page).to have_title('Home')      
    end

  end


  describe "contact page" do
    it "should have 'Contact Us' in it's contact page name " do
      visit '/static_pages/contact' 
      expect(page).to have_content('Contact Us')      
    end

    it "should have the title 'Contact Us'" do
      visit '/static_pages/contact' 
      expect(page).to have_title('Contact Us')      
    end
  end

  describe "About page" do
    it "should have 'About Us' in the about page" do
      visit '/static_pages/about'
      expect(page).to have_content('About Us')
    end

    it "should have the title 'About Us'" do
      visit '/static_pages/about' 
      expect(page).to have_title('About Us')      
    end
  end

end
